const projectData = [
  {
    id: 1,
    title: 'Weatho',
    category: 'Frontend',
    description: 'It is live weather Web App through which we can get the weather of any city.',
    image: './weather.jpg',
    technologies: ['React', 'CSS', 'Weather API'],
    demoLink: 'https://weatho2.netlify.app/',
    githubLink: 'https://github.com/your-repo',
  },
  {
    id: 2,
    title: 'MyNote',
    category: 'Mern',
    description: 'A Note App lets users create, edit, and manage notes easily. It helps organize thoughts, tasks, or reminders in one place.',
    image: './note.jpg',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB'],
    demoLink: 'https://newnoteapp-3.onrender.com/',
    githubLink: 'https://github.com/mdimteyaz6493/newnoteapp',
  },
  {
    id: 3,
    title: 'ImageUP',
    category: 'Mern',
    description: 'ImageUP is an app that allows users to upload, preview, and manage images. It’s useful for showcasing, storing, or processing images in web projects.',
   image: './imageup.jpg',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB'],
    demoLink: 'https://imageupapp.netlify.app/',
    githubLink: 'https://github.com/mdimteyaz6493/ImageupApp',
  },
   {
    id: 4,
    title: 'ChatApp',
    category: 'Mern',
    description: 'A Chat App enables real-time messaging between users. It supports features like user authentication and instant communication.',
    image: './Chatapp.jpg',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB','Socket IO'],
    demoLink: 'https://chaapp-re.onrender.com/',
    githubLink: 'https://github.com/mdimteyaz6493/chaApp',
  },
   {
    id: 5,
    title: 'RemoveBg',
    category: 'Frontend',
    description: 'Allows users to upload images and automatically remove their backgrounds using AI. It provides a clean, transparent background for easy editing.',
   image: './removebg.jpg',
    technologies: ['React', 'Css', 'Bg Remover API'],
    demoLink: 'https://ikbgremover.netlify.app/',
    githubLink: 'https://github.com/mdimteyaz6493/bgremover',
  },
   {
    id: 6,
    title: 'Qr code Generator',
    category: 'Frontend',
    description: 'It is web app through which we can generate a Qr code of any link or text etc.',
   image: './qrcode.jpg',
    technologies: ['React', 'Css'],
    demoLink: 'https://ikqrcodegen.netlify.app/#qr_sec',
    githubLink: 'https://github.com/mdimteyaz6493/qrcodegen',
  },
  {
    id: 7,
    title: 'SignaturePad',
    category: 'Frontend',
    description: 'It is Digital signature web App. You can do your signature and can easily download in png format.',
   image: './sign.jpg',
    technologies: ['Reactjs', 'Css','React-signature-canvs'],
    demoLink: 'https://signhere.netlify.app/',
    githubLink: 'https://github.com/mdimteyaz6493/Signature_pad',
  },
    {
    id: 8,
    title: 'To do list',
    category: 'Frontend',
    description: 'It is a Todo list , Where we store our todo tasks.',
   image: './todo.jpg',
    technologies: ['Html', 'Css','Js'],
    demoLink: 'https://iktodo.netlify.app',
    githubLink: 'https://github.com/mdimteyaz6493/Todo',
  },
];

export default projectData;